# Generated by Django 3.2.7 on 2021-10-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211028_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animes',
            new_name='Anime',
        ),
        migrations.RenameModel(
            old_name='filmes',
            new_name='Filme',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
