# Generated by Django 3.2.7 on 2021-10-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211028_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='idioma',
        ),
        migrations.AddField(
            model_name='anime',
            name='idioma',
            field=models.ManyToManyField(to='core.Idioma'),
        ),
        migrations.AddField(
            model_name='filme',
            name='idioma',
            field=models.ManyToManyField(to='core.Idioma'),
        ),
        migrations.AddField(
            model_name='serie',
            name='idioma',
            field=models.ManyToManyField(to='core.Idioma'),
        ),
    ]
