# Generated by Django 3.2.7 on 2021-10-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211028_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='temporada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='temporada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='genero',
            field=models.ManyToManyField(to='core.Genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='idioma',
            field=models.ManyToManyField(to='core.Idioma', verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(to='core.Genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='idioma',
            field=models.ManyToManyField(to='core.Idioma', verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.ManyToManyField(to='core.Genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='idioma',
            field=models.ManyToManyField(to='core.Idioma', verbose_name='Idioma'),
        ),
    ]
