# Generated by Django 3.2.7 on 2021-11-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211030_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='anime',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='filmes'),
        ),
        migrations.AddField(
            model_name='anime',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='filmes'),
        ),
        migrations.AddField(
            model_name='filme',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='filmes'),
        ),
        migrations.AddField(
            model_name='serie',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
