# Generated by Django 3.2.7 on 2021-11-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211128_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas'),
        ),
    ]
