# Generated by Django 3.2.7 on 2021-12-02 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20211128_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Assistindo', 'Assistindo'), ('Desistiu', 'Desistiu'), ('Concluído', 'Concluído'), ('Planejamento', 'Planejamento')], max_length=20, verbose_name='Status')),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.anime')),
                ('filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.filme')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
