# Generated by Django 3.2.7 on 2021-12-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='ep_atual',
            field=models.IntegerField(default=1, verbose_name='Ep atual'),
            preserve_default=False,
        ),
    ]
