# Generated by Django 3.2.7 on 2021-10-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211028_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='filmes',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Nota'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='genero',
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('idioma', models.CharField(choices=[('DUB', 'Dublado'), ('LEG', 'Legendado')], max_length=20, verbose_name='Idioma')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota')),
                ('quant_episodio', models.IntegerField(verbose_name='Quantidade de Episódio')),
                ('Status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status')),
                ('genero', models.ManyToManyField(to='core.Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('idioma', models.CharField(choices=[('DUB', 'Dublado'), ('LEG', 'Legendado')], max_length=20, verbose_name='Idioma')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota')),
                ('quant_episodio', models.IntegerField(verbose_name='Quantidade de Episódio')),
                ('Status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status')),
                ('genero', models.ManyToManyField(to='core.Genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='filmes',
            name='genero',
            field=models.ManyToManyField(to='core.Genero'),
        ),
    ]
