# Generated by Django 3.2.7 on 2021-10-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211030_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='temporada',
            new_name='temporadas',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='temporada',
            new_name='temporadas',
        ),
    ]
