# Generated by Django 3.2.7 on 2021-12-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_anime_ep_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='temp_atual',
            field=models.IntegerField(default=1, verbose_name='Temp atual'),
            preserve_default=False,
        ),
    ]
